export {unstable_settings} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/app/_layout'
export {ExternalLink} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/ExternalLink'
export {MonoText} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/StyledText'
export {useThemeColor, Text, View} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/Themed'
export type {TextProps, ViewProps} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/Themed'
export type {PageProps, LayoutProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/.next/types/app/page'
export type {ThemeContextType, ThemeProviderProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/providers/ColoredThemeProvider/ColoredThemeProvider'
export {shadows} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/providers/ColoredThemeProvider/colors'
export {theme} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/providers/ColoredThemeProvider/theme'
export type {TabScreens} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/app/(tabs)/_layout'
export {useAuth, withAuthProviderCheck} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/auth'
export {Provider} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/context-provider'
export {useErrorsContext} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/error-provider'
export type {ErrorsContextProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/error-provider'
export {OpenSansLight, OpenSansRegular, OpenSansBold, OpenSansCondensedLight, OpenSansCondensedRegular, OpenSansCondensedBold, MontserratBold, MontserratLight, MontserratRegular, fonts} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/theme-context'
export type {ThemeProviderForExpoProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/theme-context'
export {getFromEncryptedStorageForWeb} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/utils/storage/getFromEncryptedStorage/getFromEncryptedStorage.web'
export {removeFromEncryptedStorageForWeb} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/utils/storage/removeFromEncryptedStorage/removeFromEncryptedStorage.web'
export {removeFromStorage} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/utils/storage/removeFromStorage/removeFromStorage'
export {defaultSVGProps} from './packages/@devlander/shared-react-native-types/src/bundle/shared/defaults/svg-props.defaults'
export type {ThemeColorPreferences, ThemeProviderOptions, ThemeProviderPropsShared} from './packages/@devlander/shared-react-native-types/src/bundle/shared/providers/SharedThemeProviderCore/SharedThemeProviderCore.provider'
export {generateColorsFrom} from './packages/@devlander/shared-react-native-types/src/bundle/shared/setup/generate-colors-from'
export {AlignItemsEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/align-items.enum'
export {AutoCapitalizeEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/auto-capatlize.enum'
export {AutoCompleteTypeEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/auto-complete.enum'
export type {PaddingOnThemeType, NativeTheme, WebTheme, BoxShadowHandler, ThemeBase} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/base-theme-types'
export {ButtonVariantEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/button-variants.enum'
export type {ColorFromTheme, ValueOfColor, ColorNameOrValueFromTheme, GrayScaleColors, ElementColors, BrandColors, BackgroundColors, FeedbackColors, InteractionColors, ColorInfoItem} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/color.types'
export type {CreateThemeForNative, CreateThemeForWeb, ThemeConfig} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/create-theme.types'
export {DataDetectorEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/data-detector.enum'
export type {PlatformOSType, DeviceOnTheme} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/device-on-theme.type'
export type {ElevationType} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/elevation.type'
export {InitializationError, LogError, MessageError} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/error.types'
export type {ArrayLengthMutationKeys} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/fixed-array.type'
export {ResponsiveByPercentOrValue} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-size-handler.type'
export type {ResponsiveBy, FontSizePropsHandler} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-size-handler.type'
export {FontTypeEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-type.enum'
export type {FontName, FontProperty} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-type.enum'
export {FontTypeWeightEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-weight.enum'
export type {FontTypeWeight, FontWeightType} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-weight.enum'
export {textFontWeightTypes, TextFontWeightTypesEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-weight.types'
export type {TextFontWeightType} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/font-weight.types'
export type {FontType, FontsInterface} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/fonts.interface'
export type {NativeFunctionProvider, WebFunctionProvider} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/function-provider.types'
export {IoniconNames, FontAwesomeIconNames} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/icons/icon-names.enum'
export type {IconNames} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/icons/icon-names.enum'
export type {NameOfFontAwesomeIcon} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/icons/name-of-font-awesome-icon.type'
export type {NameOfIoniconIcon} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/icons/name-of-ionicon-icon.type'
export type {NameOfMaterialIcon} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/icons/name-of-material-icon.type'
export {JustifyContentEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/justify-content.enum'
export {KeyBoardTypeEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/keyboard-type.enum'
export {TColor} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/log-color.types'
export type {TColorValue} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/log-color.types'
export type {SVGPropsInterface} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/svg-props.interface'
export {TextDecorationLineTypes} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/text-decoration-line-types.enum'
export {TextContentTypeEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/text-field-content.enum'
export type {SharedTextProperties} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/text-style.types'
export {TextTransformTypes} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/text-transform-types.enum'
export {UnitOfMeasurementNative, UnitOfMeasurementWeb} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/unit-props.types'
export type {UnitOfMeasurement, UnitPropsHandler} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/unit-props.types'
export {cssColorNames, isConsoleAvailable, log, canBeConvertedIntoColor} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/adjust-color'
export type {ColorAdjuster} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/adjust-color'
export {calculatePercentageByPartAndWhole} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/calculate-percentage-by-part-and-whole'
export type {FontSizeCap} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/cap-font-size'
export {dashToCamelCase} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/dash-to-camel-case'
export {getErrorMessageFromErrorObject} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-from-errors-object'
export {getErrorMessageByField} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-message-by-field'
export type {ErrorMessages} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-message-by-field'
export {getErrorMessageFromErrorMessages} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-message-from-errors-messages'
export {extractKeysAndValuesFromColorsInterface} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/extract-values-from-colors-interface'
export {getFirstWordCapitalized} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/get-first-word-capitalized'
export {getLineHeight} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/get-line-height'
export {getRange} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/get-range'
export {hasLetter} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/has-letter'
export {hslToRgb} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/hsl-to-rgba'
export {ColorNameOrValueEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/is-color-name-or-value'
export {isJson} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/is-json'
export {isValidHex} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/is-valid-hex'
export {logColoredMessage, logError, logMessageBasedOnCondition} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/logger/logger'
export {RGBAToHexA} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/rbga-to-hex'
export {removeKeysWithSubstrings} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/remove-keys-with-substrings'
export {sliceIntoChunks} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/slice-into-chunks'
export {videoTimeStampToSeconds} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/video-timestamp-to-seconds'
export {withThemeFunctionsWeb} from './packages/@devlander/shared-react-native-types/src/bundle/web/hoc/withThemeFunctions.web'
export type {ComponentWithThemeFunctionsWeb, WithThemeFunctionsForWeb} from './packages/@devlander/shared-react-native-types/src/bundle/web/hoc/withThemeFunctions.web'
export {StyledProviderWithFunctionsForWeb} from './packages/@devlander/shared-react-native-types/src/bundle/web/providers/FunctionsProvider/FunctionsProvider.web'
export type {BaseWebTheme} from './packages/@devlander/shared-react-native-types/src/bundle/web/types/base-theme-interface.web'
export type {ButtonStylePropsForWeb} from './packages/@devlander/shared-react-native-types/src/bundle/web/types/button-style-props.web'
export {RFPercentageForWeb, RFValueForWeb} from './packages/@devlander/shared-react-native-types/src/bundle/web/utils/responsive-font-size.web'
export {dimensionsModuleForWeb} from './packages/@devlander/shared-react-native-types/src/bundle/web/utils/theme-functions/constant-units-for-theme.web'
export {getStyleForImgPropsForWeb} from './packages/@devlander/shared-react-native-types/src/bundle/web/utils/theme-functions/get-style-for-img-props.web'
/**
   * Title: shared-react-native-types - Auto Export Web Named Exports
   * Description: This is for exporting the web index file
   * Date: 2023-11-27
   */
  
/**
   * Start Time: 11/27/2023, 3:21:53 PM
   * End Time: 11/27/2023, 3:21:54 PM
   * Duration: 0h 0m 0s 278ms
   */
  