export {unstable_settings} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/app/_layout'
export {ExternalLink} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/ExternalLink'
export {MonoText} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/StyledText'
export {useThemeColor, Text, View} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/Themed'
export type {TextProps, ViewProps} from './packages/@devlander/shared-react-native-types/examples/apps/native-shared-types/components/Themed'
export type {PageProps, LayoutProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/.next/types/app/page'
export {metadata} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/layout'
export {defaultThemeContext} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/providers/ColoredThemeProvider/ColoredThemeProvider'
export type {ThemeContextType, ThemeProviderProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/providers/ColoredThemeProvider/ColoredThemeProvider'
export {darkTheme, shadows, lightTheme} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/providers/ColoredThemeProvider/colors'
export {theme} from './packages/@devlander/shared-react-native-types/examples/apps/react-example/src/app/providers/ColoredThemeProvider/theme'
export type {TabScreens} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/app/(tabs)/_layout'
export {useAuth, withAuthProviderCheck} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/auth'
export {Provider} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/context-provider'
export {useErrorsContext} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/error-provider'
export type {ErrorsContextProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/error-provider'
export {OpenSansLight, OpenSansRegular, OpenSansBold, OpenSansCondensedLight, OpenSansCondensedRegular, OpenSansCondensedBold, MontserratBold, MontserratLight, MontserratRegular, fonts} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/theme-context'
export type {ThemeProviderForExpoProps} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/context/theme-context'
export {getFromEncryptedStorageForNative} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/utils/storage/getFromEncryptedStorage/getFromEncryptedStorage.native'
export {removeFromEncryptedStorageForNative} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/utils/storage/removeFromEncryptedStorage/removeFromEncryptedStorage.native'
export {removeFromStorage} from './packages/@devlander/shared-react-native-types/examples/apps/react-native-example/src/utils/storage/removeFromStorage/removeFromStorage'
export {withThemeFunctionsNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/hoc/withThemeFunctions.native'
export type {ComponentWithThemeFunctionsNative, WithThemeFunctionsForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/hoc/withThemeFunctions.native'
export {StyledProviderWithFunctionsForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/providers/FunctionsProvider/FunctionsProvider.native'
export {createThemeForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/setup/create-theme/create-theme.native'
export type {BaseNativeTheme} from './packages/@devlander/shared-react-native-types/src/bundle/native/types/base-theme-interface.native'
export {isIphoneX, ifIphoneX, getStatusBarHeight, getBottomSpace, RFPercentageNative, RFValueNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/responsive-font-size.native'
export {dimensionsModuleForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/constant-units-for-theme.native'
export {getStyleForGhostPropsForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/get-style-for-ghost-props.native'
export {getStyleForImgPropsForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/get-style-for-img-props.native'
export {getStyleForTextPropsForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/get-style-for-text-props.native'
export {getStyleFromButtonPropsForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/get-style-from-button-props.native'
export {getStyleFromPropsNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/get-style-from-props.native'
export {colorThemeHandlerNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/handle-color-from-theme.native'
export {handleFontFromThemeForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/handle-font-for-theme.native'
export {handleFontSizePropsForNative} from './packages/@devlander/shared-react-native-types/src/bundle/native/utils/theme-functions/handle-font-size-props.native'
export {generateColorsFrom} from './packages/@devlander/shared-react-native-types/src/bundle/shared/setup/generate-colors-from'
export type {PaddingOnThemeType, NativeTheme, WebTheme, BoxShadowHandler, ThemeBase} from './packages/@devlander/shared-react-native-types/src/bundle/shared/types/base-theme-types'
export {cssColorNames, isConsoleAvailable, log, canBeConvertedIntoColor, adjustColor} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/adjust-color'
export type {ColorAdjuster} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/adjust-color'
export {calculatePercentageByPartAndWhole} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/calculate-percentage-by-part-and-whole'
export {capFontSize} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/cap-font-size'
export type {FontSizeCap} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/cap-font-size'
export {dashToCamelCase} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/dash-to-camel-case'
export {getErrorMessageFromErrorObject} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-from-errors-object'
export {getErrorMessageByField} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-message-by-field'
export type {ErrorMessages} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-message-by-field'
export {getErrorMessageFromErrorMessages} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/errors/get-error-message-from-errors-messages'
export {extractKeysAndValuesFromColorsInterface} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/extract-values-from-colors-interface'
export {getFirstWordCapitalized} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/get-first-word-capitalized'
export {getLineHeight} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/get-line-height'
export {getRange} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/get-range'
export {boxShadowOne} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/handle-box-shadows'
export {unitPropsHandler} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/handle-unit-props'
export {hasLetter} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/has-letter'
export {hslToRgb} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/hsl-to-rgba'
export {isColorNameOrValue, ColorNameOrValueEnum} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/is-color-name-or-value'
export {isJson} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/is-json'
export {isValidHex} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/is-valid-hex'
export {logColoredMessage, logError, logMessageBasedOnCondition} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/logger/logger'
export {RGBAToHexA} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/rbga-to-hex'
export {removeKeysWithSubstrings} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/remove-keys-with-substrings'
export {sliceIntoChunks} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/slice-into-chunks'
export {videoTimeStampToSeconds} from './packages/@devlander/shared-react-native-types/src/bundle/shared/utils/video-timestamp-to-seconds'
/**
   * Title: shared-react-native-types - Auto Export Native Default Exports for bundleAsObjectForDefaultExport
   * Description: This is for exporting the native index file
   * Date: 2023-11-29
   */
  
/**
   * Start Time: 11/29/2023, 7:19:55 AM
   * End Time: 11/29/2023, 7:19:55 AM
   * Duration: 0h 0m 0s 83ms
   */
  